name: deploy-project

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CI_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CI_CLIENT_SECRET }}
          tags: tag:ci

      - name: starting SSH agent
        shell: bash
        run: |
            mkdir -p ~/.ssh
            eval $(ssh-agent)

      - name: Adding known host
        shell: bash
        run: |
          ssh-keyscan -p 22 "nyx.tuatara-puffin.ts.net" >> ~/.ssh/known_hosts

      # TODO: something like:
      # ssh patrick@nyx.tuatara-puffin.ts.net "if [ ! -d /opt/gitops/nyx ]; then mkdir /opt/gitops && git clone https://github.com/p2-network/nyx /opt/gitops/nyx; fi"
      # but... permissions.
      
      - name: Remote Deployment
        shell: bash
        run: |
          ssh patrick@nyx.tuatara-puffin.ts.net "cd /opt/gitops/nyx && git pull && ci/update.sh"
